const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),cp=require('child_process');
const root=process.cwd();
for(const f of fs.readdirSync(root).filter(f=>f.endsWith('.js')).concat(['worker/src/index.js','worker/src/game-monitor.js','worker/src/mlb.js','worker/src/push-service.js']))cp.execFileSync('node',['--check',f]);
let snapshot;const sends=[];let failed=new Set();
const ctx={console,Response,Request,URL,Date,DurableObject:class{},fetchGameSnapshot:async()=>structuredClone(snapshot),isFinalGame:s=>/final/i.test(s?.abstractState||''),isLiveGame:s=>/live/i.test(s?.abstractState||'')};
vm.createContext(ctx);vm.runInContext('function on(t,n,f,o){t.addEventListener(n,f,o)}; var ManagedResizeObserver=typeof ResizeObserver!=="undefined"?ResizeObserver:null;',ctx);let src=fs.readFileSync('worker/src/game-monitor.js','utf8').replace(/import \{ DurableObject \} from "cloudflare:workers";/,'').replace(/import \{[\s\S]*?\} from "\.\/mlb.js";/,'').replace('export class GameMonitor','globalThis.GameMonitor = class GameMonitor');vm.runInContext(src,ctx);
function monitor(){const data=new Map();let alarm=null;const storage={get:async k=>structuredClone(data.get(k)),put:async(k,v)=>{if(typeof k==='object')for(const [key,val]of Object.entries(k))data.set(key,structuredClone(val));else data.set(k,structuredClone(v));},setAlarm:async a=>alarm=a,deleteAlarm:async()=>alarm=null,getAlarm:async()=>alarm};return {m:new ctx.GameMonitor({storage},{PUSH_SERVICE:{idFromName:n=>{assert.equal(n,'global');return n},get:()=>({fetch:async r=>{assert.equal(new URL(r.url).pathname,'/send');const b=await r.json();sends.push(b);return Response.json({results:b.subscriptions.map(s=>({endpoint:s.endpoint,ok:!failed.has(s.endpoint),expired:s.endpoint.includes('expired')}))});}})}}),data,storage,get alarm(){return alarm}}}
const base=(state='Preview',a=0,h=0)=>({gamePk:123,abstractState:state,gameDate:new Date(Date.now()+4*60000).toISOString(),awayName:'A',homeName:'H',awayScore:a,homeScore:h});
const watch=(id)=>new Request('https://internal/watch',{method:'POST',body:JSON.stringify({gamePk:123,deviceId:id,subscription:{endpoint:'https://push/'+id,keys:{p256dh:'x',auth:'y'}}})});
(async()=>{
const o=monitor();snapshot=base();await o.m.watch(watch('one'));assert.equal(sends[0].payload.stage,'subscription');assert.equal(sends[0].payload.title,'A vs H｜訂閱成功');assert.equal(sends.at(-1).payload.stage,'pregame5');assert(o.alarm);const n=sends.length;await o.m.checkGame();assert.equal(sends.length,n);await o.m.watch(watch('one'));assert.equal(sends.length,n,'duplicate watch resent confirmation');
snapshot=base('Live');await o.m.checkGame();assert.equal(sends.at(-1).payload.stage,'start');assert(o.alarm-Date.now()<=5000);
snapshot=base('Live',1,0);await o.m.checkGame();assert.equal(sends.at(-1).payload.stage,'score');snapshot=base('Live',1,2);await o.m.checkGame();assert.equal(sends.at(-1).payload.stage,'score');
snapshot=base('Final',1,3);const before=sends.length;await o.m.checkGame();assert.deepEqual(sends.slice(before).map(x=>x.payload.stage),['score','final']);assert.equal(o.data.get('subscribers').length,0);assert.equal(o.alarm,null);
const late=monitor();snapshot=base('Live',4,3);const l=sends.length;await late.m.watch(watch('late'));assert.deepEqual(sends.slice(l).map(x=>x.payload.stage),['subscription'],'late subscriber received old score/start');
snapshot=base('Live',5,3);await late.m.watch(watch('new'));const recent=sends.at(-1);assert.equal(recent.payload.stage,'score');assert.deepEqual(recent.subscriptions.map(s=>s.endpoint),['https://push/late']);
failed.add('https://push/late');snapshot=base('Final',6,3);const r=sends.length;await late.m.checkGame();assert.deepEqual(sends.slice(r).map(x=>x.payload.stage),['score','final']);assert.equal(sends.at(-1).subscriptions.length,1);assert.equal(late.data.get('subscribers').length,1);assert(late.alarm);
failed.clear();const rr=sends.length;await late.m.checkGame();assert.deepEqual(sends.slice(rr).map(x=>x.payload.stage),['score','final']);assert.equal(late.data.get('subscribers').length,0);
const far=monitor();snapshot={...base(),gameDate:new Date(Date.now()+3600000).toISOString()};await far.m.watch(watch('far'));assert.equal(far.alarm,Date.parse(snapshot.gameDate)-300000);let status=await (await far.m.watchStatus(new Request('https://internal/watch/status?deviceId=far'))).json();assert(status.subscribed);await far.m.unwatch(new Request('https://internal/watch',{method:'DELETE',body:JSON.stringify({deviceId:'far'})}));assert.equal(far.alarm,null);status=await(await far.m.watchStatus(new Request('https://internal/watch/status?deviceId=far'))).json();assert.equal(status.subscribed,false);
const confirmation=monitor();snapshot={...base(),gameDate:new Date(Date.now()+3600000).toISOString()};failed.add('https://push/retry');await confirmation.m.watch(watch('retry'));assert.equal(confirmation.data.get('subscribers')[0].sent.subscription,false);assert(confirmation.alarm-Date.now()<=30000);failed.clear();const retryCount=sends.length;await confirmation.m.checkGame();assert.deepEqual(sends.slice(retryCount).map(x=>x.payload.stage),['subscription']);assert.equal(confirmation.data.get('subscribers')[0].sent.subscription,true);await confirmation.m.unwatch(new Request('https://internal/watch',{method:'DELETE',body:JSON.stringify({deviceId:'retry'})}));const resubCount=sends.length;await confirmation.m.watch(watch('retry'));assert.deepEqual(sends.slice(resubCount).map(x=>x.payload.stage),['subscription']);
const legacy=monitor();snapshot=base('Live',2,1);await legacy.storage.put({gamePk:123,lastSnapshot:snapshot,subscribers:[{deviceId:'old',subscription:{endpoint:'https://push/old'},sent:{start:true,pregame5:true,final:false}}]});const oldCount=sends.length;await legacy.m.checkGame();assert.equal(sends.length,oldCount,'legacy subscription received confirmation');
console.log('PASS: subscription confirmation, retry, duplicate suppression, resubscribe, legacy compatibility;  JS syntax, pregame, start, both scores, score-before-final, cleanup, late baseline, per-device baseline, failed score retry, status, cancel, alarms, DO forwarding');
})().catch(e=>{console.error(e);process.exit(1)});

