const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
(async () => {
  const {parseChannelVideos, matchesGame, getGameHighlights, MLB_CHANNEL_ID} = await import('../worker/src/highlights.js');
  const game = {gamePk:123, officialDate:'2026-10-07',doubleHeader:'N',gameNumber:1,status:{abstractGameState:'Final'},teams:{away:{team:{id:119,name:'Los Angeles Dodgers',teamName:'Dodgers'}},home:{team:{id:144,name:'Atlanta Braves',teamName:'Braves'}}}};
  const video = {id:'cv8qfCAzrmM',title:'DODGERS vs. BRAVES: Division Series Full Game 4 Highlights (October 7) | 2026 MLB Postseason',description:'Dodgers vs. Braves full game 4 highlights from 10/7/26',duration:'19:32'};
  assert(matchesGame(video,game));
  for (const title of ['Dodgers vs. Braves Shorts Recap','Dodgers vs. Braves Full 2026 NLDS Highlights','Dodgers vs. Braves FULL INNING Highlights (October 7) 2026','Padres vs. Brewers Game Highlights (October 7) 2026']) assert(!matchesGame({...video,title},game), title);
  assert(!matchesGame(video,{...game,officialDate:'2026-10-06'}));
  assert(!matchesGame(video,{...game,officialDate:'2025-10-07'}));
  const regular = {...video,title:'Dodgers vs. Braves Game Highlights (10/7/26)',description:''};
  assert(matchesGame(regular,game));
  assert(!matchesGame(regular,{...game,doubleHeader:'Y',gameNumber:1}));
  assert(matchesGame({...regular,title:'Dodgers vs. Braves Game 2 Highlights (10/7/26)'},{...game,doubleHeader:'Y',gameNumber:2}));
  assert(!matchesGame({...regular,title:'Dodgers vs. Braves Game 2 Highlights (10/7/26)'},{...game,doubleHeader:'Y',gameNumber:1}));
  const renderer = owner => ({videoRenderer:{videoId:video.id,title:{simpleText:video.title},descriptionSnippet:{simpleText:video.description},lengthText:{simpleText:video.duration},ownerText:{runs:[{navigationEndpoint:{browseEndpoint:{browseId:owner}}}]}}});
  const html = (owner=MLB_CHANNEL_ID) => '<script>var ytInitialData = '+JSON.stringify({metadata:{channelMetadataRenderer:{externalId:MLB_CHANNEL_ID}},contents:[renderer(owner)]})+';</script>';
  assert.equal(parseChannelVideos(html()).length,1);
  assert.equal(parseChannelVideos(html('unofficial')).length,0);
  assert.throws(()=>parseChannelVideos('<html>blocked</html>'));
  assert.throws(()=>parseChannelVideos(html().replaceAll(MLB_CHANNEL_ID,'wrong')));
  let requests=0;
  const cached=new Map();const cache={match:async r=>cached.get(r.url)?.clone(),put:async(r,s)=>cached.set(r.url,s)};
  global.fetch=async url=>{requests++;return new Response(url.includes('statsapi')?JSON.stringify({dates:[{games:[game]}]}):html());};
  const data=await getGameHighlights(123,cache);assert.equal(data.videos.length,1);
  await getGameHighlights(123,cache);assert.equal(requests,2,'cached request fetched upstream');
  game.status.abstractGameState='Live';assert.equal((await getGameHighlights(123)).status,'not-final');
  assert.equal(requests,3,'non-final should not query YouTube');

  const list={innerHTML:'',insertAdjacentHTML:(_,s)=>list.innerHTML+=s};
  const context={console,Date,Map,Number,String,AbortSignal,PUSH_API:'https://worker.test',els:{recapList:list,recapSummary:{}},state:{selectedGamePk:123,currentFeedGamePk:123,currentFeed:{gameData:{status:{abstractGameState:'Final'},teams:game.teams}}},esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),syncLiveDetailHeight:()=>{},requestAnimationFrame:f=>f()};
  const pending = new Map();
  context.fetch=url=>new Promise(resolve=>pending.set(Number(url.split('/').pop()),resolve));
  vm.createContext(context);vm.runInContext(fs.readFileSync('highlights.js','utf8'),context);
  const first=context.loadGameRecap();
  context.state.selectedGamePk=124;context.state.currentFeedGamePk=124;
  const second=context.loadGameRecap();
  pending.get(124)({ok:true,json:async()=>({...data,videos:[{...video,title:'new game <script>'}]})});await second;
  pending.get(123)({ok:true,json:async()=>data});await first;
  assert(list.innerHTML.includes('new game &lt;script&gt;'));
  assert(!list.innerHTML.includes('DODGERS vs.'),'stale game result overwrote selected game');
  assert(list.innerHTML.includes('target="_blank"'));
  context.state.currentFeed.gameData.status.abstractGameState='Live';await context.loadGameRecap();assert(list.innerHTML.includes('尚未結束'));
  context.renderGameRecap({status:'pending',videos:[]});assert(list.innerHTML.includes('尚未找到'));
  context.renderGameRecap({videos:[{id:'javascript:bad',title:'bad'}]});assert(!list.innerHTML.includes('javascript:'));
  context.state.currentFeed.gameData.status.abstractGameState='Final';context.fetch=async()=>({ok:false});await context.loadGameRecap(true);assert(list.innerHTML.includes('暫時無法'));
  context.resetGameRecap();assert(list.innerHTML.includes('目前沒有'));
  console.log('PASS highlights: official source, exact game/date, doubleheader, filtering, cache, stale response, HTML escaping, loading states');
})().catch(error=>{console.error(error);process.exit(1)});
